name: wokflow-push-3

on:
  workflow_call:
    inputs:
      tag: # id of input
        description: 'Tag of the master branch'
        required: false
        default: ''
        type: string

jobs:
  Manual-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Check
        run: |
          echo "Code is being deployed from ${{ inputs.tag }}"
