name: wokflow-push-2

on:
  workflow_call:
    inputs:
      tag: # id of input
        description: 'Tag of the master branch'
        required: true
        default: ''
        type: string

jobs:
  Manual-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Check test
        run: |
          echo "Code is being deployed from ${{ inputs.tag }}"
